[workspace]
authors = ["udit-asopa <udit.asopa@gmail.com>"]
channels = ["conda-forge"]
name = "google_kaggle_agentic_ai"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
faiss-cpu = ">=1.9.0,<2"
transformers = ">=4.56.0,<5"
sentence-transformers = ">=5.1.0,<6"
accelerate = ">=1.10.1,<2"
datasets = ">=4.0.0,<5"
langchain = ">=0.3.27,<0.4"
openai = ">=1.102.0,<2"
tiktoken = ">=0.9.0,<0.10"
pydantic = ">=2.11.7,<3"
pandas = ">=2.3.2,<3"
numpy = ">=1.26.4,<2"
scikit-learn = ">=1.7.1,<2"
python-dotenv = ">=1.1.1,<2"
typer = ">=0.16.1,<0.17"
pathlib = ">=1.0.1,<2"
kaggle = ">=1.7.4.5,<2"
kagglehub = ">=0.3.8,<0.4"
google-adk = ">=1.14.1,<2"
jupyter = ">=1.1.1,<2"
google-genai = ">=1.49.0,<2"

[pypi-dependencies]
dotenv = ">=0.9.9, <0.10"
